sudo: required
services:
  - docker

before_install:
  - docker build -t leminh/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true leminh/docker-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-testing'
  env: 'DockerTesting-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-773934793312'
  bucket_path: 'docker-testing'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
